force-app/main/default/objects/History__c/History__c.object-meta.xml
<CustomObject>
    <label>History</label>
    <nameField>
        <displayFormat>HI{000000}</displayFormat>
        <label>History Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/History__c/fields/InvestmentId__c.field-meta.xml
<CustomField>
    <fullName>InvestmentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>History</relationshipLabel>
    <relationshipName>History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/CurrentValue__c.field-meta.xml
<CustomField>
    <fullName>CurrentValue__c</fullName>
    <label>Current Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Networth_Handler.cls
public with sharing class Networth_Handler {
    
    public static Double calculateInvestmentValue(date queryDate) {
        Double returnValue = 0;

        Investment__c[] investments = Investment_Handler.getActiveInvestments(queryDate);

        for(Investment__c investment:investments) {
            if(investment.History__r.size() == 1) {
                returnValue += investment.History__r[0].Value__c;
            } else {
                returnValue += investment.CurrentValue__c;
            }
        }

        return returnValue;
    }
}