force-app/main/default/objects/History__c/History__c.object-meta.xml
<CustomObject>
    <label>History</label>
    <nameField>
        <displayFormat>HI{000000}</displayFormat>
        <label>History Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/History__c/fields/FromDate__c.field-meta.xml
<CustomField>
    <fullName>FromDate__c</fullName>
    <label>From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/History__c/fields/InvestmentId__c.field-meta.xml
<CustomField>
    <fullName>InvestmentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>History</relationshipLabel>
    <relationshipName>History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/History__c/fields/ToDate__c.field-meta.xml
<CustomField>
    <fullName>ToDate__c</fullName>
    <label>To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <label>Investment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/CurrentValue__c.field-meta.xml
<CustomField>
    <fullName>CurrentValue__c</fullName>
    <label>Current Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/CurrentValueRefreshDate__c.field-meta.xml
<CustomField>
    <fullName>CurrentValueRefreshDate__c</fullName>
    <label>Current Value Refresh Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/PurchaseDate__c.field-meta.xml
<CustomField>
    <fullName>PurchaseDate__c</fullName>
    <label>Purchase Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/SoldDate__c.field-meta.xml
<CustomField>
    <fullName>SoldDate__c</fullName>
    <label>Sold Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Investment_Handler.cls
public with sharing class Investment_Handler {
    public static Investment__c[] getActiveInvestments(Date queryDate) {
        return [SELECT Id, 
                    CurrentValue__c,
                    PurchaseDate__c,
                    SoldDate__c,
                    CurrentValueRefreshDate__c,
                    (SELECT Value__c FROM History__r WHERE FromDate__c <= :queryDate AND ToDate__c >: queryDate ORDER BY ToDate__c DESC LIMIT 1)
                FROM Investment__c  
                WHERE PurchaseDate__c <= :queryDate
                AND (SoldDate__c >= :queryDate OR SoldDate__c = NULL) WITH SECURITY_ENFORCED];
    }
}