force-app/main/default/objects/BudgetItem__c/BudgetItem__c.object-meta.xml
<CustomObject>
    <label>Budget Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BudgetItem__c/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <label>Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BudgetItem__c/fields/PaymentFrequency__c.field-meta.xml
<CustomField>
    <fullName>PaymentFrequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BudgetItem__c/fields/PerMonth__c.field-meta.xml
<CustomField>
    <fullName>PerMonth__c</fullName>
    <formula>Amount__c / Interval__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Per Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BudgetItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>Expenditure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>One Off</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Half Yearly</fullName>
    </customValue>
    <customValue>
        <fullName>Yearly</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BudgetItem_Handler.cls
public with sharing class BudgetItem_Handler {
    
    @AuraEnabled(cacheable=true)
    public static BudgetItem__c[] getAllBudgetItems() {
        return [SELECT Id, Name, StartDate__c, EndDate__c, Amount__c, PaymentFrequency__c, PerMonth__c, Interval__c FROM BudgetItem__c];
    }

    @AuraEnabled(cacheable=true)
    public static BudgetItem__c[] getIncomeBudgetItems() {
        return [SELECT Id, Name, StartDate__c, EndDate__c, Amount__c, PaymentFrequency__c, PerMonth__c, Interval__c FROM BudgetItem__c WHERE Type__c = 'Income'];
    }

    @AuraEnabled(cacheable=true)
    public static BudgetItem__c[] getExpenditureBudgetItems() {
        return [SELECT Id, Name, StartDate__c, EndDate__c, Amount__c, PaymentFrequency__c, PerMonth__c, Interval__c FROM BudgetItem__c WHERE Type__c = 'Expenditure'];
    }

    public static void validate(BudgetItem__c[] budgetItems) {
        for(BudgetItem__c budgetItem:budgetItems){
            validate(budgetItem);
        }
    }

    public static void validate(BudgetItem__c budgetItem) {
        if(budgetItem.StartDate__c > budgetItem.EndDate__c && budgetItem.EndDate__c != null) {
            budgetItem.addError('The item\'s End Date must be after the item\'s Start Date.');
        }
    }

    public static void setDefaults(BudgetItem__c[] budgetItems) {
        for(BudgetItem__c budgetItem:budgetItems){
            setDefaults(budgetItem);
        }
    }

    public static void setDefaults(BudgetItem__c budgetItem) {
        setInterval(budgetItem);
    }

    public static void setInterval(BudgetItem__c budgetItem) {
        switch on budgetItem.PaymentFrequency__c {
            when  'One Off' {
                budgetItem.Interval__c = 1;
            }
            when  'Monthly' {
                budgetItem.Interval__c = 1;
            }
            when  'Quarterly' {
                budgetItem.Interval__c = 3;
            }
            when  'Half Yearly' {
                budgetItem.Interval__c = 6;
            }
            when  'Yearly' {
                budgetItem.Interval__c = 12;
            }
            when else {
                budgetItem.Interval__c = budgetItem.Interval__c;
            }
        }
    } 
}